[2025-03-03T19:21:29.761-0500] {processor.py:186} INFO - Started process (PID=89835) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:21:29.762-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:21:29.762-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:21:29.762-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:21:29.773-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:21:29.773-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:21:29.773-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:21:29.773-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:21:29.773-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:21:29.796-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-03-03T19:23:17.248-0500] {processor.py:186} INFO - Started process (PID=90190) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:23:17.249-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:23:17.249-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:23:17.249-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:23:17.261-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:23:17.261-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:23:17.261-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:23:17.261-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:23:17.261-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:23:17.284-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-03-03T19:26:05.793-0500] {processor.py:186} INFO - Started process (PID=90868) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:26:05.794-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:26:05.795-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:26:05.795-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:26:05.807-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:26:05.807-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:26:05.807-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:26:05.807-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:26:05.807-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:26:05.831-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-03-03T19:28:28.004-0500] {processor.py:186} INFO - Started process (PID=91438) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:28:28.005-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:28:28.006-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:28:28.006-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:28:28.018-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:28:28.018-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:28:28.018-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:28:28.018-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:28:28.018-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:28:28.043-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-03-03T19:30:16.077-0500] {processor.py:186} INFO - Started process (PID=91771) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:30:16.079-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:30:16.079-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:30:16.079-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:30:16.091-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:30:16.091-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:30:16.091-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:30:16.091-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:30:16.091-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:30:16.115-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-03-03T19:32:46.037-0500] {processor.py:186} INFO - Started process (PID=92288) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:32:46.038-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:32:46.039-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:32:46.039-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:32:46.050-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:32:46.050-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:32:46.051-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:32:46.051-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:32:46.051-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:32:46.074-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-03-03T19:34:35.893-0500] {processor.py:186} INFO - Started process (PID=92531) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:34:35.894-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:34:35.894-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:34:35.894-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:34:35.907-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:34:35.907-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:34:35.907-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:34:35.907-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:34:35.907-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:34:35.931-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-03-03T19:37:13.184-0500] {processor.py:186} INFO - Started process (PID=92890) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:37:13.185-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:37:13.186-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:37:13.186-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:37:13.198-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:37:13.198-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:37:13.198-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:37:13.198-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:37:13.198-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:37:13.222-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-03-03T19:39:55.540-0500] {processor.py:186} INFO - Started process (PID=93264) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:39:55.541-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:39:55.541-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:39:55.541-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:39:55.554-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:39:55.553-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:39:55.554-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:39:55.554-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:39:55.554-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:39:55.577-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-03-03T19:42:41.938-0500] {processor.py:186} INFO - Started process (PID=93872) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:42:41.939-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:42:41.939-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:42:41.939-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:42:41.951-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:42:41.951-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:42:41.951-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:42:41.951-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:42:41.951-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:42:41.974-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-03-03T19:44:34.249-0500] {processor.py:186} INFO - Started process (PID=94090) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:44:34.251-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:44:34.251-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:44:34.251-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:44:34.263-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:44:34.263-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:44:34.263-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:44:34.263-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:44:34.263-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:44:34.286-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-03-03T19:49:09.119-0500] {processor.py:186} INFO - Started process (PID=94748) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:49:09.120-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:49:09.121-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:49:09.121-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:49:09.132-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:49:09.132-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:49:09.132-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:49:09.132-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:49:09.132-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:49:09.155-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-03-03T19:50:58.707-0500] {processor.py:186} INFO - Started process (PID=94883) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:50:58.708-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:50:58.709-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:50:58.708-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:50:58.720-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:50:58.719-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:50:58.720-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:50:58.720-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:50:58.720-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:50:58.742-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-03-03T19:53:39.387-0500] {processor.py:186} INFO - Started process (PID=95228) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:53:39.388-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:53:39.388-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:53:39.388-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:53:39.400-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:53:39.400-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:53:39.400-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:53:39.400-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:53:39.400-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:53:39.423-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-03-03T19:56:23.321-0500] {processor.py:186} INFO - Started process (PID=95650) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:56:23.322-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:56:23.322-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:56:23.322-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:56:23.334-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:56:23.334-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:56:23.335-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:56:23.335-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:56:23.335-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:56:23.357-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-03-03T19:59:07.665-0500] {processor.py:186} INFO - Started process (PID=95967) to work on /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:59:07.666-0500] {processor.py:914} INFO - Processing file /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-03T19:59:07.666-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:59:07.666-0500] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:59:07.678-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:59:07.678-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-03T19:59:07.679-0500] {logging_mixin.py:190} INFO - [2025-03-03T19:59:07.679-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-03T19:59:07.679-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-03T19:59:07.702-0500] {processor.py:208} INFO - Processing /Users/kartikvadhawana/anaconda3/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
